sonar.projectKey=sotoAron_Parcial-TDD-ICS
sonar.organization=sotoaron

# Le decimos que analice la carpeta actual
sonar.sources=.
# Excluimos las dependencias y las pruebas para que no arroje falsos positivos
sonar.exclusions=node_modules/**, tests/**, features/**
# Donde esta la configuración para el análisis de cobertura de código 
sonar.javascript.lcov.reportPaths=coverage/lcov.info