sonar.projectKey=sotoAron_Parcial-TDD-ICS
sonar.organization=sotoaron

# 1. Le decimos que busque en la carpeta actual
sonar.sources=.

# 2. EL ESCUDO: Ignorar librerías, reportes y configuraciones para el análisis de calidad
sonar.exclusions=node_modules/**, coverage/**, tests/**, .github/**, eslint.config.js, openapi.yaml

# 3. Le indicamos dónde están nuestras pruebas para que las cuente como tests, no como código de producción
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# 4. La ruta del reporte de cobertura que generamos en el paso anterior
sonar.javascript.lcov.reportPaths=coverage/lcov.info